{
    "th06_01": "A Dream More Scarlet than Red",
    "th06_02": "A Soul as Scarlet as a Ground Cherry",
    "th06_03": "Apparitions Stalk the Night",
    "th06_04": "Lunate Elf",
    "th06_05": "Tomboyish Girl in Love",
    "th06_06": "Shanghai Scarlet Teahouse ~ Chinese Tea",
    "th06_07": "Shanghai Alice of Meiji 17",
    "th06_08": "Voile, the Magic Library",
    "th06_09": "Locked Girl ~ The Girl's Sealed Room",
    "th06_10": "The Maid and the Pocket Watch of Blood",
    "th06_11": "Lunar Clock ~ Luna Dial",
    "th06_12": "The Young Descendant of Țepeș",
    "th06_13": "Septette for a Dead Princess",
    "th06_14": "The Centennial Festival for Magical Girls",
    "th06_15": "U.N. Owen was Her?",
    "th06_16": "An Eternity More Transient than Scarlet",
    "th06_17": "Scarlet Chamber ~ Eastern Dream...",
    "th07_01": "Ghostly Dream ~ Snow or Cherry Petal",
    "th07_02": "Paradise ~ Deep Mountain",
    "th07_03": "Crystallized Silver",
    "th07_04": "The Fantastic Tales from Tōno",
    "th07_05": "Diāo Yè Zōng (withered leaf)",
    "th07_06": "The Doll Maker of București",
    "th07_07": "Doll Judgment ~ The Girl Who Played with People's Shapes",
    "th07_08": "The Capital City of Flowers in the Sky",
    "th07_09": "Phantom Band ~ Phantom Ensemble",
    "th07_10": "Eastern Ghostly Dream ~ Ancient Temple",
    "th07_11": "Hiroari Shoots a Strange Bird ~ Till When?",
    "th07_12": "Ultimate Truth",
    "th07_13": "Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life",
    "th07_14": "Border of Life",
    "th07_15": "Spiritual Domination",
    "th07_16": "A Maiden's Illusionary Funeral ~ Necro-Fantasy",
    "th07_17": "Spiritual Domination ~ Who done it!",
    "th07_18": "Necrofantasia",
    "th07_19": "Dream of a Spring Breeze",
    "th07_20": "Sakura, Sakura ~ Japanize Dream...",
    "th08_01": "Eternal Night Vignette ~ Eastern Night",
    "th08_02": "Illusionary Night ~ Ghostly Eyes",
    "th08_03": "Wriggling Autumn Moon ~ Mooned Insect",
    "th08_04": "Song of the Night Sparrow ~ Night Bird",
    "th08_05": "Deaf to All but the Song",
    "th08_06": "Nostalgic Blood of the East ~ Old World",
    "th08_07": "Plain Asia",
    "th08_08": "Retribution for the Eternal Night ~ Imperishable Night",
    "th08_09": "Maiden's Capriccio ~ Dream Battle",
    "th08_10": "Love-Colored Master Spark",
    "th08_11": "Cinderella Cage ~ Kagome-Kagome",
    "th08_12": "Lunatic Eyes ~ Invisible Full Moon",
    "th08_13": "Voyage 1969",
    "th08_14": "Gensokyo Millennium ~ History of the Moon",
    "th08_15": "Flight of the Bamboo Cutter ~ Lunatic Princess",
    "th08_16": "Voyage 1970",
    "th08_17": "Extend Ash ~ Person of Hourai",
    "th08_18": "Reach for the Moon, Immortal Smoke",
    "th08_19": "Evening Primrose",
    "th08_20": "Eternal Dream ~ Mystical Maple",
    "th08_21": "Eastern Youkai Beauty",
    "th09_01": "Flower Reflecting Mound ~ Higan Retour",
    "th09_02": "Spring Lane ~ Colorful Path",
    "th09_03": "Oriental Dark Flight",
    "th09_04": "Flowering Night",
    "th09_05": "Eastern Ghostly Dream ~ Ancient Temple",
    "th09_06": "Lunatic Eyes ~ Invisible Full Moon",
    "th09_07": "Adventure of the Lovestruck Tomboy",
    "th09_08": "Phantom Band ~ Phantom Ensemble",
    "th09_09": "Deaf to All but the Song ~ Flower Mix",
    "th09_10": "White Flag of Usa Shrine",
    "th09_11": "Wind God Girl",
    "th09_12": "Poison Body ~ Forsaken Doll",
    "th09_13": "Gensokyo, Past and Present ~ Flower Land",
    "th09_14": "Higan Retour ~ Riverside View",
    "th09_15": "Eastern Judgement in the Sixtieth Year ~ Fate of Sixty Years",
    "th09_16": "The Mound where the Flowers Reflect",
    "th09_17": "Mound of Shigan",
    "th09_18": "The Flowers Remain in Fantasy",
    "th09_19": "Flower of Soul ~ Another Dream...",
    "th095_01": "Tengu's Notebook ~ Mysterious Note",
    "th095_02": "Wind Circulation ~ Wind Tour",
    "th095_03": "Tengu is Watching ~ Black Eyes",
    "th095_04": "Sleepless Night of the Eastern Country",
    "th095_05": "Retrospective Kyoto",
    "th095_06": "Wind God Girl",
    "th10_01": "Sealed Gods",
    "th10_02": "A God That Misses People ~ Romantic Fall",
    "th10_03": "Because Princess Inada Is Scolding Me",
    "th10_04": "The Road of the Misfortune God ~ Dark Road",
    "th10_05": "Dark Side of Fate",
    "th10_06": "The Gensokyo the Gods Loved",
    "th10_07": "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
    "th10_08": "Fall of Fall ~ Autumnal Waterfall",
    "th10_09": "Youkai Mountain ~ Mysterious Mountain",
    "th10_10": "The Primal Scene of Japan the Girl Saw",
    "th10_11": "Faith Is for the Transient People",
    "th10_12": "Cemetery of Onbashira ~ Grave of Being",
    "th10_13": "The Venerable Ancient Battlefield ~ Suwa Foughten Field",
    "th10_14": "Tomorrow Will Be Special, Yesterday Was Not",
    "th10_15": "Native Faith",
    "th10_16": "Shrine at the Foot of the Mountain",
    "th10_17": "The Gods Give Us Blessed Rain ~ Sylphid Dream",
    "th10_18": "Player's Score",
    "th11_01": "Awakening of the Earth Spirits",
    "th11_02": "The Dark Blowhole",
    "th11_03": "The Sealed-Away Youkai ~ Lost Place",
    "th11_04": "The Bridge People No Longer Cross",
    "th11_05": "Green-Eyed Jealousy",
    "th11_06": "Walking the Streets of a Former Hell",
    "th11_07": "A Flower-Studded Saké Dish on Mt. Ooe",
    "th11_08": "Heartfelt Fancy",
    "th11_09": "Satori Maiden ~ 3rd eye",
    "th11_10": "Lullaby of Deserted Hell",
    "th11_11": "Corpse Voyage ~ Be of good cheer!",
    "th11_12": "Hellfire Mantle",
    "th11_13": "Solar Sect of Mystic Wisdom ~ Nuclear Fusion",
    "th11_14": "Last Remote",
    "th11_15": "Hartmann's Youkai Girl",
    "th11_16": "The Earth Spirits' Homecoming",
    "th11_17": "Energy Daybreak ~ Future Dream...",
    "th12_01": "A Shadow in the Blue Sky",
    "th12_02": "At the Harbor of Spring",
    "th12_03": "A Tiny, Tiny, Clever Commander",
    "th12_04": "The Sealed Cloud Route",
    "th12_05": "Beware the Umbrella Left There Forever",
    "th12_06": "Sky Ruin",
    "th12_07": "The Traditional Old Man and the Stylish Girl",
    "th12_08": "Interdimensional Voyage of a Ghostly Passenger Ship",
    "th12_09": "Captain Murasa",
    "th12_10": "Rural Makai City Esoteria",
    "th12_11": "The Tiger-Patterned Bishamonten",
    "th12_12": "Fires of Hokkai",
    "th12_13": "Emotional Skyscraper ~ Cosmic Mind",
    "th12_14": "UFO Romance in the Night Sky",
    "th12_15": "Heian Alien",
    "th12_16": "Youkai Temple",
    "th12_17": "Returning Home from the Sky ~ Sky Dream",
    "th125_01": "Newshound",
    "th125_02": "The Mystery in Your Town",
    "th125_03": "Youkai Modern Colony",
    "th125_04": "Nemesis's Stronghold",
    "th125_05": "Bell of Avīci ~ Infinite Nightmare",
    "th125_06": "Youkai Mountain ~ Mysterious Mountain",
    "th128_01": "An Ice Fairy in Spring",
    "th128_02": "The Refrain of the Lovely Great War",
    "th128_03": "Staking Your Life on a Prank",
    "th128_04": "Year-Round Absorbed Curiosity",
    "th128_05": "A Midnight Fairy Dance",
    "th128_06": "Great Fairy Wars ~ Fairy Wars",
    "th128_07": "Loose Rain",
    "th128_08": "Magus Night",
    "th128_09": "An Ice Fairy in Spring - still -",
    "th128_10": "Player's Score",
    "th13_01": "Spirit of Avarice",
    "th13_02": "Night Sakura of Dead Spirits",
    "th13_03": "Ghost Lead",
    "th13_04": "Welcome to Youkai Temple",
    "th13_05": "Youkai Girl at the Gate",
    "th13_06": "Let's Live in a Lovely Cemetery",
    "th13_07": "Rigid Paradise",
    "th13_08": "Desire Drive",
    "th13_09": "Old Yuanxian",
    "th13_10": "The Hall of Dreams' Great Mausoleum",
    "th13_11": "Omiwa Legend",
    "th13_12": "Starry Sky of Small Desires",
    "th13_13": "Shoutoku Legend ~ True Administrator",
    "th13_14": "Youkai Shrine's Back Road",
    "th13_15": "Futatsuiwa from Sado",
    "th13_16": "A New Wind at the Shrine",
    "th13_17": "Desire Dream",
    "th14_01": "Mysterious Purification Rod",
    "th14_02": "Mist Lake",
    "th14_03": "Mermaid from the Uncharted Land",
    "th14_04": "Humans and Youkai Traversing the Canal",
    "th14_05": "Dullahan Under the Willows",
    "th14_06": "Bamboo Forest of the Full Moon",
    "th14_07": "Lonesome Werewolf",
    "th14_08": "Magical Storm",
    "th14_09": "Illusionary Joururi",
    "th14_10": "The Shining Needle Castle Sinking in the Air",
    "th14_11": "Reverse Ideology",
    "th14_12": "The Exaggerated Castle Keep",
    "th14_13": "Inchlings of the Shining Needle ~ Little Princess",
    "th14_14": "Thunderclouds of Magical Power",
    "th14_15": "Primordial Beat ~ Pristine Beat",
    "th14_16": "Magical Power of the Mallet",
    "th14_17": "Mysterious, Mysterious Tools",
    "th143_01": "Raise the Signal Fire of Cheating",
    "th143_02": "Cheat Against the Impossible Danmaku",
    "th143_03": "Midnight Spell Card",
    "th143_04": "Romantic Escape Flight",
    "th143_05": "Eternal Transient Reign",
    "th143_06": "Mermaid from the Uncharted Land",
    "th143_07": "Reverse Ideology",
    "th143_08": "Illusionary Joururi",
    "th143_09": "Youkai Mountain ~ Mysterious Mountain",
    "th15_01": "The Space Shrine Maiden Appears",
    "th15_02": "Unforgettable, the Nostalgic Greenery",
    "th15_03": "The Rabbit Has Landed",
    "th15_04": "The Lake Reflects the Cleansed Moonlight",
    "th15_05": "September Pumpkin",
    "th15_06": "The Mysterious Shrine Maiden Flying Through Space",
    "th15_07": "Eternal Spring Dream",
    "th15_08": "The Frozen Eternal Capital",
    "th15_09": "Reversed Wheel of Fortune",
    "th15_10": "Faraway Voyage of 380,000 Kilometers",
    "th15_11": "Pierrot of the Star-Spangled Banner",
    "th15_12": "The Sea that Reflects One's Home Planet",
    "th15_13": "Pure Furies ~ Whereabouts of the Heart",
    "th15_14": "A World of Nightmares Never Seen Before",
    "th15_15": "Pandemonic Planet",
    "th15_16": "The Moon as Seen from the Shrine",
    "th15_17": "The Space Shrine Maiden Returns Home",
    "th16_01": "The Sky Where Cherry Blossoms Flutter Down",
    "th16_02": "A Star of Hope Rises in the Blue Sky",
    "th16_03": "A Midsummer Fairy's Dream",
    "th16_04": "The Colorless Wind on Youkai Mountain",
    "th16_05": "Deep-Mountain Encounter",
    "th16_06": "Swim in a Cherry Blossom-Colored Sea",
    "th16_07": "A Pair of Divine Beasts",
    "th16_08": "Illusionary White Traveler",
    "th16_09": "The Magic Straw-Hat Jizo",
    "th16_10": "Does the Forbidden Door Lead to This World, or the World Beyond?",
    "th16_11": "Crazy Backup Dancers",
    "th16_12": "Into Backdoor",
    "th16_13": "The Concealed Four Seasons",
    "th16_14": "No More Going Through Doors",
    "th16_15": "Secret God Matara ~ Hidden Star in All Seasons.",
    "th16_16": "Unnatural Nature",
    "th16_17": "White Traveler",
    "th135_02": "Spring Lane ~ Colorful Path",
    "th135_03": "Magus Night",
    "th135_04": "The Traditional Old Man and the Stylish Girl",
    "th135_05": "Emotional Skyscraper ~ Cosmic Mind",
    "th135_06": "Omiwa Legend",
    "th135_07": "Shoutoku Legend ~ True Administrator",
    "th135_08": "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
    "th135_09": "Hartmann's Youkai Girl",
    "th135_10": "Futatsuiwa from Sado",
    "th135_11": "Futatsuiwa from Gensokyo",
    "th135_12": "The Lost Emotion",
    "th135_13": "This Dull World's Unchanging Pessimism",
    "th135_14": "Shinkirou Orchestra",
    "th135_15": "Morning Clouds",
    "th135_16": "Officially-Sanctioned Twilight Newspaper",
    "th135_17": "Today's Front-Page Headline",
    "th135_19": "A Popular Location",
    "th135_20": "An Unpopular Location",
    "th135_22": "The Village in the Dead of Night",
    "th135_23": "Performer Selection",
    "th135_34": "Last Word Unleashed",
    "th105_01": "Heaven of Scarlet Perception",
    "th105_02": "Usual Days",
    "th105_03": "The Ground's Color is Yellow",
    "th105_04": "Argue for and Against",
    "th105_05": "Beautiful Nature Sight",
    "th105_06": "Fragrant Plants",
    "th105_07": "Dancing Water Spray",
    "th105_08": "Swing a Fish to Drive Away Flies",
    "th105_09": "Free and Easy",
    "th105_10": "Ridiculous Game",
    "th105_11": "Drunk as I Like",
    "th105_12": "Skies Beyond the Clouds",
    "th105_13": "Crimson in the Black Sea ~ Legendary Fish",
    "th105_14": "Flawless as Clothing of the Celestials",
    "th105_15": "Catastrophe in Bhavaagra ~ Wonderful Heaven",
    "th105_16": "Bhavaagra As Seen Through a Child's Mind",
    "th105_17": "Darkening Dusk",
    "th105_18": "Eastern Heaven of Scarlet Perception",
    "th105_19": "Eastern Mystical Tale of Romance",
    "th105_20": "Vessel of Stars ~ Casket of Star",
    "th105_21": "Flowering Night",
    "th105_22": "The Doll Maker of București",
    "th105_23": "Hiroari Shoots a Strange Bird ~ Till When?",
    "th105_24": "Locked Girl ~ The Girl's Sealed Room",
    "th105_25": "Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life",
    "th105_26": "Septette for a Dead Princess",
    "th105_27": "Night Falls ~ Evening Star",
    "th105_28": "Broken Moon",
    "th105_29": "Lunatic Eyes ~ Invisible Full Moon",
    "th105_30": "Wind God Girl",
    "th105_31": "Higan Retour ~ Riverside View",
    "th123_01": "Did You See that Shadow?",
    "th123_02": "Forgathering Dream",
    "th123_03": "The Legendary Titan",
    "th123_04": "Faith Is for the Transient People",
    "th123_05": "Tomboyish Girl in Love",
    "th123_06": "Scenery with Dolls",
    "th123_07": "Shanghai Scarlet Teahouse ~ Chinese Tea",
    "th123_08": "Solar Sect of Mystic Wisdom ~ Nuclear Fusion",
    "th123_09": "Our Hisoutensoku",
    "th123_10": "Unknown X ~ Unfound Adventure",
    "th123_11": "X, the Floating Object in the Sky",
    "th123_12": "Dichromatic Lotus Butterfly ~ Ancients",
    "th123_13": "Love-Colored Magic",
    "th123_14": "the Grimoire of Alice",
    "th123_15": "Voile, the Magic Library",
    "th123_16": "Tomorrow Will Be Special, Yesterday Was Not",
    "th123_17": "The Eternal Steam Engine",
    "th123_18": "A Huge Shadow and a Tiny Conclusion",
    "th123_19": "Eastern Mystical Tale of Romance (Century's End Version)",
    "th075_01": "Forgathering Dream",
    "sh01_18": "Dichromatic Lotus Butterfly ~ Ancients",
    "th02_09": "Love-Colored Magic",
    "th05_17": "the Grimoire of Alice",
    "th03_03": "Eastern Mystical Tale of Romance",
    "th04_11": "Vessel of Stars ~ Casket of Star",
    "th075_17": "Night Falls ~ Evening Star",
    "th075_34": "Broken Moon",
    "th155_01": "Dichromatic Lotus Butterfly ~ Red and White",
    "th155_02": "Love-Colored Master Spark",
    "th155_03": "The Traditional Old Man and the Stylish Girl",
    "th155_05": "Omiwa Legend",
    "th155_07": "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
    "th155_09": "Futatsuiwa from Gensokyo",
    "th155_08": "Hartmann's Youkai Girl",
    "th155_06": "Shoutoku Legend ~ True Administrator",
    "th155_04": "Emotional Skyscraper ~ Cosmic Mind",
    "th155_11": "Reach for the Moon, Immortal Smoke",
    "th155_13": "Battlefield of the Flower Threshold",
    "th155_12": "Inchlings of the Shining Needle ~ Little Princess",
    "th155_16": "Eternal Spring Dream",
    "th155_18": "Night Falls ~ Evening Star",
    "th155_19": "The Ground's Color is Yellow ~ Primrose",
    "th155_15": "Lunatic Eyes ~ Invisible Full Moon",
    "th155_14": "Last Occultism ~ Esotericist of the Present World",
    "th155_10": "The Lost Emotion",
    "th155_17": "Catastrophe in Bhavaagra ~ Wonderful Heaven",
    "th155_41": "Unknown X ~ Occultly Madness",
    "th155_38": "Occult Attract",
    "th155_40": "Bell of Aeons",
    "th155_39": "Neo Bamboo Forest in Flames",
    "th155_22": "Equality Under the Law of Dharma",
    "th155_21": "The Palanquin Ship Flies in the Sky",
    "th155_20": "Mushroom Waltz",
    "th155_24": "Shining Armillary Sphere",
    "th155_25": "The Ravine Kappa's Technological Prowess",
    "th155_26": "A Rose Blooming in the Underworld",
    "th155_37": "Tonight Stars an Easygoing Egoist (Live ver.) ~ Egoistic Flowers.",
    "th155_36": "Yorimashi Between Dreams and Reality ~ Necro-Fantasia",
    "th155_35": "Bhavaagra as Far as the Eye Can See",
    "th155_34": "Sleep Sheep Parade",
    "th155_33": "Corridor Stretching to Eternity",
    "th155_32": "Dream World Folklore",
    "th155_31": "Overcome a Thousand Trials",
    "th155_30": "The Inverted Castle Lit by the Setting Sun",
    "th155_29": "Immortal Red Soul",
    "th155_28": "Shinkirou Theatrical",
    "th155_27": "In the Deep-Green Tanuki Forest",
    "th155_23": "Constant and Unchanging Temple of Worship",
    "th155_58": "The Eternal Steam Engine",
    "th155_50": "Flawless as Clothing of the Celestials ~ Yellow Lily",
    "th155_42": "Being Things Eye To Eye",
    "th155_43": "The One Jointly Responsible",
    "th155_44": "An Odd Couple",
    "th155_45": "Two Minds of One Body",
    "th155_46": "Grandiloquence",
    "th155_47": "Scheming Outside the Box",
    "th155_48": "In High Spirits",
    "th155_49": "The Curtain Shall Rise Soon",
    "th155_51": "Seeds of the Incident",
    "th155_52": "Sprouts of Suspicion",
    "th155_53": "Branches Reaching to the Truth",
    "th155_54": "Blizzard of Scattering Possession Flowers",
    "th155_55": "Floating with the Tide",
    "th155_56": "Possession Flowers Yet to Bud",
    "th155_57": "Possession Flowers in Full Bloom",
    "none": "(none)",
    "th_main": "Theme of Eastern Story",
    "th01_12a": "We Shall Die Together",
    "th02_01": "Eastern Demon-Sealing Record ~ Pure Land Mandala",
    "th02_10": "Eastern Demon-Sealing Record ~ Spectral Boisterous Dance",
    "th03_14": "Adoration of Magic",
    "th03_21": "Ghostly Person's Holiday",
    "th05_03": "Magic Square",
    "mcd_03_03": "Shanghai Scarlet Teahouse ~ Chinese Tea",
    "mcd_02_01": "Passing On through the Dendera Fields in the Night",
    "mcd_02_04": "Ancient Temple of the Netherworld",
    "mcd_02_06": "Merry the Magician",
    "mcd_02_11": "Eternal Festival of Illusions",
    "mcd_03_05": "Boys and Girls of the Age of Science",
    "mcd_03_09": "Border Between Dreams and Reality",
    "th125_07": "Hatate Unlock",
    "mcd_07_01": "Green Sanatorium",
    "th165_05": "\"Old Adam\" Bar",
    "th165_06": "The Darkness Brought in by Swallowstone Naturalis Historia",
    "th165_07": "Eternal Spring Dream",
    "th165_08": "The Concealed Four Seasons",
    "th165_04": "Nightmare Diary",
    "th165_03": "Lunatic Dreamer",
    "th165_02": "Lucid Dreamer",
    "th165_01": "Diary of Nightmares",
    "mcd_08_11": "Eternal Transient Reign",
    "mcd_03_02": "Dream of Huaxu",
    "th03_06": "Tabula rasa ~ The Empty Girl",
    "th03_08": "Vanishing Dream ~ Lost Dream",
    "th03_09": "Visionary Game ~ Dream War",
    "th03_11": "Decisive Magic Battle! ~ Fight it out!",
    "th04_15": "Faint Dream ~ Inanimate Dream",
    "th04_16": "The Inevitably Forbidden Game",
    "th04_17": "Illusion of a Maid ~ Icemilk Magic",
    "th16_18": "Player's Score",
    "th15_18": "Player's Score",
    "th145_28": "The Lost Emotion",
    "th145_27": "Futatsuiwa from Gensokyo",
    "th02_02": "Hakurei ~ Eastern Wind",
    "th145_ps4_07": "Madness of Visages ~ Horrible Night",
    "mcd_09_09": "Popularity Boom / Ichirin Kumoi & Unzan",
    "thmj_01": "Curious Old Shanghai Tile",
    "mcd_09_02": "The Darkness Brought in by Swallowstone Naturalis Historia",
    "th03_01": "A Dream Transcending Spacetime",
    "th05_14": "End of the World ~ World's End",
    "th075_18": "The Fabled Land of Onigashima ~ Missing Power",
    "mcd_baijr_03": "Flower Reflecting Mound ~ after Higan Retour",
    "th02_06": "World of Fantasies",
    "th05_01": "Bizarre Romantic Story ~ Mystic Square",
    "sh01_06": "Illusion of Flowers, Sky of Scarlet Dreams",
    "sh01_01": "Autumn Frost Orb ~ Clockworks",
    "sh01_04": "Fantastic Imperial Capital",
    "sh01_14": "Fantasy Science ~ Doll's Phantom",
    "sh02_01": "Rare Venerable Orb ~ Fairy Dance",
    "sh02_02": "Velvet Maiden's War ~ Velvet Battle",
    "mcd_03_10": "Fantasy Machine ~ Phantom Factory",
    "th17_01": "Silent Beast Spirits",
    "th17_02": "The Lamentations Known Only to Jizo",
    "th17_03": "Jelly Stone",
    "th17_04": "Lost River",
    "th17_05": "The Stone Baby and the Submerged Bovine",
    "th17_06": "Everlasting Red Spider Lily",
    "th17_07": "Seraphic Chicken",
    "mcd_08_05": "An Instant that Exceeds Planck's Time",
    "mcd_09_01": "\"Old Adam\" Bar",
    "th145_16": "Last Occultism ~ Esotericist of the Present World",
    "th17_08": "Unlocated Hell",
    "th17_09": "Tortoise Dragon ~ Fortune and Misfortune",
    "th17_10": "Beast Metropolis",
    "th17_11": "Joutoujin of Ceramics",
    "th17_12": "Electric Heritage",
    "th17_13": "Entrust this World to Idols ~ Idolatrize World",
    "th17_15": "Prince Shoutoku's Pegasus ~ Dark Pegasus",
    "th17_16": "The Animals' Rest",
    "th17_17": "Return from the Underground",
    "th17_18": "Player's Score",
    "th17_14": "The Shining Law of the Strong Eating the Weak",
    "th18_07": "Smoking Dragon",
    "th18_04": "The Cliff Hidden in Deep Green",
    "th18_03": "Kitten of Great Fortune",
    "th18_02": "A Shower of Strange Occurrences",
    "th18_01": "A Rainbow Spanning Gensokyo",
    "th18_06": "The Perpetual Snow of Komakusa Blossoms",
    "th18_05": "Banditry Technology",
    "mcd_scoow02_02": "Retribution for the Eternal Night ~ Pipes and Fiddle.",
    "th18_08": "The Obsolescent Industrial Ruins",
    "th18_09": "Ore from the Age of the Gods",
    "th18_10": "The Long-Awaited Oumagatoki",
    "th18_11": "Starry Mountain of Tenma",
    "th18_12": "Lunar Rainbow",
    "th18_13": "Where Is That Bustling Marketplace Now ~ Immemorial Marketeers",
    "th18_14": "The Great Fantastic Underground Railway Network",
    "th18_15": "The Princess Who Slays Dragon Kings",
    "th18_16": "The Sunday after the Storm",
    "th18_17": "A Rainbow-Colored World",
    "th18_18": "Player's Score",
    "th135_01": "This Dull World's Unchanging Pessimism ~ Shinkirou Orchestra",
    "th135_18": "Shinkirou Festival Orchestra",
    "th135_21": "An Unused Location",
    "mcd_scoow01_01": "New Year's Cherry Blossoms",
    "mcd_scoow01_02": "Insulator",
    "mcd_scoow02_01": "Occult Attract",
    "mcd_scoow02_03": "Last Occultism ~ Esotericist of the Present World",
    "mcd_fs_01": "Bibliophile with a Deciphering Eye",
    "mcd_fs_02": "Humans and Youkai Traversing the Canal",
    "mcd_fs_03": "The Rabbit Has Landed",
    "mcd_scoow03_01": "Kid's Festival ~ Innocent Treasures",
    "mcd_scoow03_02": "Mist Lake",
    "mcd_scoow03_03": "A Drunkard's Lemuria",
    "mcd_scoow04_02": "Lifeless Surface",
    "mcd_scoow04_03": "The Reality of The End and The Past",
    "mcd_scoow04_01": "The Harvest That Goes Around",
    "mcd_scoow05_01": "Whirlwind Keyboard Girl",
    "mcd_scoow05_02": "Hartmann's Sleeping Girl",
    "mcd_scoow05_03": "Necrofantasia",
    "mcd_scoow01_03": "PLAIN ASIA (2015 ALR REWIND REMIX)",
    "th175_01": "Submerged Hell of Sunken Sorrow",
    "th175_02": "Eastern Strange Tale of Avarice",
    "th175_03": "Laws of Nature, Desires of Man",
    "th175_04": "Magician's Melancholy",
    "th175_05": "The Dark Blowhole",
    "th175_06": "Walking the Streets of a Former Hell",
    "th175_07": "Hellfire Mantle",
    "th175_08": "Cemetery of Onbashira ~ Grave of Being",
    "th175_09": "Depths of the Earth, Ocean of Avarice",
    "th175_10": "Everlasting Red Spider Lily",
    "th175_11": "The Centennial Festival for Magical Girls",
    "th175_12": "Maiden's Capriccio ~ Dream Battle",
    "th175_13": "Love-Colored Master Spark",
    "th175_14": "The Sealed-Away Youkai ~ Lost Place",
    "th175_15": "Beware the Umbrella Left There Forever",
    "th175_16": "Captain Murasa",
    "th175_17": "The Venerable Ancient Battlefield ~ Suwa Foughten Field",
    "th175_18": "Tonight Stars an Easygoing Egoist (Live ver.) ~ Egoistic Flowers.",
    "th175_19": "A Flower-Studded Saké Dish on Mt. Ooe",
    "th175_20": "Solar Sect of Mystic Wisdom ~ Nuclear Fusion",
    "th175_21": "Seraphic Chicken",
    "th175_22": "U.N. Owen was Her?",
    "th175_23": "Memento of the Avaricious Beast",
    "th175_24": "Memento of All Organisms ~ Memory of Fossil Energy.",
    "th185_01": "The Collector's Melancholy Afternoon",
    "th185_02": "An Exciting and Familiar Gensokyo",
    "th185_03": "Youkai Hook On",
    "th185_04": "Black Markets Can Happen Anywhere, Anytime",
    "th185_05": "Take Thy Danmaku In Hand, O Bulletphiles",
    "th185_06": "The 100th Black Market",
    "th185_07": "Lunatic Dreamer",
    "th185_08": "Lunar Rainbow",
    "th185_09": "Where Is That Bustling Marketplace Now ~ Immemorial Marketeers",
    "th185_10": "A Rainbow-Colored World",
    "mcd_095_01": "The Wolves of Nanatsuishi Dash to Seize the Clouds",
    "mcd_095_02": "Illusionary White Traveler",
    "mcd_095_03": "Where Is That Bustling Marketplace Now ~ Immemorial Marketeers",
    "th175_25": "No More Going Through Doors",
    "th175_26": "Secret God Matara",
    "th19_01": "A Beast's Intelligence",
    "th19_02": "The World Is Made in an Adorable Way",
    "th19_03": "Magical Beast Scramble",
    "mcd_01_04": "Shanghai Alice of Meiji 17",
    "th06_07/en": "Shanghai Alice of Meiji 17",
    "th01_05": "Eastern Tale of Fancy",
    "mcd_01_05": "Eastern Tale of Fancy",
    "th01_05/en": "Eastern Strange Discourse",
    "tmgc_01": "Witch of Love Potion",
    "mcd_01_09": "Witch of Love Potion",
    "tmgc_01/en": "Witch of Love Potion",
    "mcd_01_11": "U.N. Owen was Her?",
    "th06_15/en": "U.N. Owen was Her?",
    "th01_02": "Eternal Shrine Maiden",
    "mcd_01_12": "Eternal Shrine Maiden",
    "th01_02/en": "Eternal Shrine Maiden",
    "mcd_02_03": "Eastern Ghostly Dream ~ Ancient Temple",
    "th075_13": "Eastern Ghostly Dream ~ Ancient Temple",
    "th07_10/en": "Eastern Mystical Dream ~ Ancient Temple",
    "sh01_11": "Magical Girl's Crusade",
    "mcd_02_09": "Magical Girl's Crusade",
    "sh01_11/en": "Magical Girl's Crusade",
    "mcd_02_10": "A Maiden's Illusionary Funeral ~ Necro-Fantasy",
    "th07_16/en": "A Maiden's Illusionary Funeral ~ Necro-Fantasy",
    "mcd_02_05": "Illusionary Night ~ Ghostly Eyes",
    "mcd_02_05/en": "Illusionary Night ~ Ghostly Eyes",
    "th075_02": "Eastern Mystical Tale of Romance",
    "th03_03/en": "Eastern Mystical Love Consultation",
    "th04_10": "Maiden's Capriccio ~ Capriccio",
    "th075_03": "Maiden's Capriccio ~ Capriccio",
    "th04_10/en": "Maiden's Capriccio",
    "th075_04": "Love-Colored Magic",
    "th02_09/en": "Love-colored Magic",
    "th075_06": "The Maid and the Pocket Watch of Blood",
    "th06_10/en": "The Maid and the Pocket Watch of Blood",
    "th075_07": "Lunar Clock ~ Luna Dial",
    "th06_11/en": "Lunar Clock ~ Luna Dial",
    "th075_08": "The Doll Maker of București",
    "th07_06/en": "The Doll Maker of Bucuresti",
    "th075_10": "Locked Girl ~ The Girl's Sealed Room",
    "mcd_04_09": "Locked Girl ~ The Girl's Sealed Room",
    "th06_09/en": "Locked Girl ~ The Girl's Secret Room",
    "th075_11": "Voile, the Magic Library",
    "th06_08/en": "Voile, the Magic Library",
    "th075_12": "Hiroari Shoots a Strange Bird ~ Till When?",
    "th07_11/en": "Hiroari Shoots a Strange Bird ~ Till When?",
    "th075_14": "Septette for a Dead Princess",
    "th06_13/en": "Septette for a Dead Princess",
    "th075_15": "Bloom Nobly, Ink-Black Cherry Blossom ~ Border of Life",
    "th07_13/en": "Bloom Nobly, Ink-black Cherry Blossom ~ Border of Life",
    "th06_06/en": "Shanghai Teahouse ~ Chinese Tea",
    "mcd_03_04": "Voyage 1969",
    "th08_13/en": "Voyage 1969",
    "mcd_03_06": "Retribution for the Eternal Night ~ Imperishable Night",
    "th08_08/en": "Retribution for the Eternal Night ~ Imperishable Night",
    "mcd_03_07": "Night Falls ~ Evening Star",
    "th075_17/en": "Night Falls ~ Evening Star",
    "mcd_03_08": "Doll Judgment ~ The Girl Who Played with People's Shapes",
    "th07_07/en": "Doll Judgment ~ The Girl who Played with People's Shapes",
    "th145_ps4_01": "Lunatic Eyes ~ Invisible Full Moon",
    "th08_12/en": "Lunatic Eyes ~ Invisible Full Moon",
    "th07_09/en": "Ghostly Band ~ Phantom Ensemble",
    "mcd_baijr_01": "Wind God Girl",
    "th09_11/en": "Wind God Girl",
    "mcd_baijr_02": "Adventure of the Lovestruck Tomboy",
    "th09_07/en": "Adventure of the Lovestruck Tomboy",
    "mcd_04_03": "Flight of the Bamboo Cutter ~ Lunatic Princess",
    "th08_15/en": "Flight in the Bamboo Cutter ~ Lunatic Princess",
    "mcd_04_04": "Higan Retour ~ Riverside View",
    "th09_14/en": "Higan Retour ~ Riverside View",
    "mcd_04_06": "White Flag of Usa Shrine",
    "th09_10/en": "White Flag of Usa Shrine",
    "mcd_04_07": "Reach for the Moon, Immortal Smoke",
    "th145_29": "Reach for the Moon, Immortal Smoke",
    "th08_18/en": "Reach for the Moon, Immortal Smoke",
    "mcd_04_08": "Retrospective Kyoto",
    "th095_05/en": "Retrospective Kyoto",
    "mcd_04_10": "Gensokyo Millennium ~ History of the Moon",
    "th08_14/en": "Gensokyo Millennium ~ History of the Moon",
    "mcd_05_03": "Sleepless Night of the Eastern Country",
    "th095_04/en": "Sleepless Night of the Eastern Country",
    "th075_16": "Demystify Feast",
    "mcd_05_05": "Demystify Feast",
    "th075_16/en": "Demystify Feast",
    "mcd_05_09": "Necrofantasia",
    "th07_18/en": "Necrofantasia",
    "th04_11/en": "Vessel of Stars ~ Casket of Star",
    "th09_04/en": "Flowering Night",
    "th075_34/en": "Broken Moon",
    "th11_18": "Player's Score",
    "th12_18": "Player's Score",
    "th13_18": "Player's Score",
    "th14_18": "Player's Score",
    "th10_18/en": "Player's Score",
    "mcd_fairy01_01": "Sunny Rutile Flection",
    "mcd_fairy03_02": "Sunny Rutile Flection",
    "mcd_fairy01_01/en": "Sunny Rutile Flection",
    "mcd_fairy01_02": "Can't Sleep Because It's Nighttime",
    "mcd_fairy03_03": "Can't Sleep Because It's Nighttime",
    "mcd_fairy01_02/en": "Can't Sleep Because It's Nighttime",
    "mcd_fairy01_03": "Like the Brilliance of Fairies",
    "mcd_fairy03_04": "Like the Brilliance of Fairies",
    "mcd_fairy01_03/en": "Like the Brilliance of Fairies",
    "sh01_08": "Illusionary Sputnik Night",
    "mcd_gom_02": "Illusionary Sputnik Night",
    "sh01_08/en": "Illusionary Sputnik Night",
    "th075_01/en": "Memory of Forgathering Dream",
    "th10_11/en": "Faith Is for the Transient People",
    "th06_05/en": "Tomboyish Girl in Love",
    "th11_13/en": "Solar Sect of Mystic Wisdom ~ Nuclear Fusion",
    "sh01_18/en": "Dichromatic Lotus Butterfly ~ Ancients",
    "th05_17/en": "the Grimoire of Alice",
    "mcd_055_03": "Tomorrow Will Be Special, Yesterday Was Not",
    "th10_14/en": "Tomorrow Will Be Special, Yesterday Was Not",
    "th10_09/en": "Youkai Mountain ~ Mysterious Mountain",
    "mcd_fairy05_02": "Youkai Modern Colony",
    "th125_03/en": "Youkai Modern Colony",
    "mcd_fairy03_01": "The Refrain of the Lovely Great War",
    "mcd_fairy03_01/en": "The Refrain of the Lovely Great War",
    "mcd_fairy06_01": "Year-Round Absorbed Curiosity",
    "th128_04/en": "Year-Round Absorbed Curiosity",
    "mcd_fairy06_02": "A Midnight Fairy Dance",
    "th128_05/en": "A Midnight Fairy Dance",
    "mcd_fairy06_03": "Great Fairy Wars ~ Fairy Wars",
    "th128_06/en": "Great Fairy Wars ~ Fairy Wars",
    "mcd_055_02": "Bell of Avīci ~ Infinite Nightmare",
    "th125_05/en": "Bell of Avici ~ Infinite Nightmare",
    "mcd_fairy07_01": "Magus Night",
    "th128_08/en": "Magus Night",
    "mcd_fairy07_02": "Staking Your Life on a Prank",
    "th128_03/en": "Staking Your Life on a Prank",
    "mcd_fairy07_03": "Old Yuanxian",
    "th13_09/en": "Gu Yuan Xian ~ Old Distant Hermit",
    "mcd_06_03": "Desire Drive",
    "th13_08/en": "Desire Drive",
    "mcd_fairy04_01": "The Fairy's Adventurous Tale",
    "mcd_06_04": "The Fairy's Adventurous Tale",
    "mcd_fairy04_01/en": "The Fairy's Adventurous Tale",
    "mcd_06_06": "UFO Romance in the Night Sky",
    "th12_14/en": "UFO Romance in the Night Sky",
    "mcd_06_07": "Hartmann's Youkai Girl",
    "th145_26": "Hartmann's Youkai Girl",
    "th11_15/en": "Hartmann's Youkai Girl",
    "mcd_06_09": "Emotional Skyscraper ~ Cosmic Mind",
    "th145_22": "Emotional Skyscraper ~ Cosmic Mind",
    "th12_13/en": "Emotional Skyscraper ~ Cosmic Mind",
    "mcd_07_03": "Heartfelt Fancy",
    "th11_08/en": "Heartfelt Fancy",
    "mcd_07_04": "Eastern Judgement in the Sixtieth Year ~ Fate of Sixty Years",
    "th09_15/en": "Eastern Judgment in the Sixtieth Year ~ Fate of Sixty Years",
    "mcd_07_07": "Youkai Shrine's Back Road",
    "th13_14/en": "Youkai Back Shrine Road",
    "mcd_07_08": "Unknown X ~ Unfound Adventure",
    "th123_10/en": "Unknown X ~ Unfound Adventure",
    "mcd_07_10": "Let's Live in a Lovely Cemetery",
    "th13_06/en": "Let's Live in a Lovely Cemetery",
    "th09_02/en": "Spring Lane ~ Colorful Path",
    "th145_21": "The Traditional Old Man and the Stylish Girl",
    "th12_07/en": "The Traditional Old Man and the Stylish Girl",
    "th145_23": "Omiwa Legend",
    "mcd_09_05": "Omiwa Legend",
    "th13_11/en": "Legend of the Great Gods",
    "th145_24": "Shoutoku Legend ~ True Administrator",
    "th13_13/en": "Shoutoku Legend ~ True Administrator",
    "th145_25": "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
    "th10_07/en": "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
    "th13_15/en": "Futatsuiwa from Sado",
    "mcd_09_03": "Reverse Ideology",
    "mcd_01_02": "Dichromatic Lotus Butterfly ~ Red and White",
    "th145_19": "Dichromatic Lotus Butterfly ~ Red and White",
    "mcd_01_02/en": "Dichromatic Lotus Butterfly ~ Red and White",
    "th145_20": "Love-Colored Master Spark",
    "th08_10/en": "Love-colored Master Spark",
    "th145_30": "Inchlings of the Shining Needle ~ Little Princess",
    "mcd_08_02": "The Frozen Eternal Capital",
    "mcd_08_04": "September Pumpkin",
    "mcd_08_07": "The Shining Needle Castle Sinking in the Air",
    "mcd_08_09": "The Sea that Reflects One's Home Planet",
    "mcd_08_10": "Pure Furies ~ Whereabouts of the Heart",
    "th145_ps4_04": "Occult Attract",
    "th145_ps4_04/ja": "Occult Attract",
    "mcd_09_06": "Pandemonic Planet",
    "mcd_09_08": "Rural Makai City Esoteria",
    "th12_10/en": "Rural Makai City Esoteria",
    "th135_26": "Popularity Boom / Ichirin Kumoi & Unzan",
    "mcd_03_01": "Kid's Festival ~ Innocent Treasures",
    "mcd_03_01/en": "Kid's Festival ~ Innocent Treasures",
    "alcostg_06": "A Drunkard's Lemuria",
    "alcostg_06/en": "A Drunkard's Lemuria",
    "th145_14": "Battlefield of the Flower Threshold",
    "th105_15/en": "Catastrophe in Bhavaagra ~ Wonderful Heaven",
    "th145_ps4_02": "Neo Bamboo Forest in Flames",
    "th145_ps4_02/ja": "Neo Bamboo Forest in Flames",
    "th145_ps4_03": "Bell of Aeons",
    "th145_ps4_03/ja": "Bell of Aeons",
    "th145_ps4_06": "Unknown X ~ Occultly Madness",
    "th145_ps4_06/ja": "Unknown X ~ Occultly Madness",
    "th123_17/en": "The Eternal Steam Engine",
    "mcd_gom_01": "Magician's Melancholy",
    "mcd_gom_01/en": "Magician's Melancholy",
    "th11_02/en": "The Dark Blowhole",
    "th11_06/en": "Walking the Streets of a Former Hell",
    "th11_12/en": "Hellfire Mantle",
    "th10_12/en": "Cemetery of Onbashira ~ Grave of Being",
    "th06_14/en": "The Centennial Festival for Magical Girls",
    "th08_09/en": "Maiden's Capriccio ~ Dream Battle",
    "th11_03/en": "The Sealed-Away Youkai ~ Lost Place",
    "th12_05/en": "Beware the Umbrella Left There Forever",
    "th12_09/en": "Captain Murasa",
    "th10_13/en": "The Venerable Ancient Battlefield ~ Suwa Foughten Field",
    "th11_07/en": "A Flower-Studded Sake Dish on Mt. Ooe",
    "th19_04": "The Oni on the Perpetual Mountain",
    "th19_05": "Tiny Shangri-La",
    "th12_02/en": "At the End of Spring",
    "th19_06": "A Brave and Leisurely Beast",
    "th19_10": "The Primal Scene of Japan the Girl Saw",
    "th19_17": "Futatsuiwa from Sado",
    "th19_11": "Spiritual Domination ~ Who done it!",
    "th07_17/en": "Youkai Domination ~ Who done it!",
    "th19_12": "A Pair of Divine Beasts",
    "th19_13": "At the Harbor of Spring",
    "th19_14": "Unforgettable, the Nostalgic Greenery",
    "th19_15": "Corpse Voyage ~ Be of good cheer!",
    "th11_11/en": "Corpse Voyage ~ Be of good cheer!",
    "th19_16": "The Long-Awaited Oumagatoki",
    "th19_18": "Tortoise Dragon ~ Fortune and Misfortune",
    "th19_20": "Memento of the Avaricious Beast",
    "th19_07": "Vampiric Cryptid Chupacabra",
    "th19_21": "The Beast Kings' Rest",
    "th19_22": "Do Beasts Have Intelligence?",
    "th19_09": "The Deviants' Unobstructed Light ~ Kingdom of Nothingness",
    "th19_08": "The Path to Yomi Where None Turn Back",
    "th19_19": "Prince Shoutoku's Pegasus ~ Dark Pegasus",
    "th10_10/en": "The Primal Scene of Japan the Girl Saw",
    "mcd_scoow06_03": "Necrofantasia",
    "mcd_10_10": "The Concealed Four Seasons",
    "mcd_10_03": "Does the Forbidden Door Lead to This World, or the World Beyond?",
    "mcd_10_04": "Smoking Dragon",
    "mcd_10_06": "Crazy Backup Dancers",
    "mcd_10_07": "Yorimashi Between Dreams and Reality ~ Necro-Fantasia",
    "mcd_10_09": "The Lamentations Known Only to Jizo",
    "mcd_scoow06_01": "Morning Star Rocket",
    "mcd_10_01": "Dawn Breaks on Tanabatazaka",
    "mcd_10_02": "Tinkerbell of Inequality",
    "mcd_10_05": "Mugen Noh ~ Taboo Marionette",
    "mcd_10_08": "The Lonely Road of Hitachi",
    "mcd_10_11": "Ghosts Exist Even When It's Not Night",
    "mcd_02_07": "Uncanny Bird of the Moon, Illusion of the Bakeneko",
    "mcd_02_02": "Girls' Secret Sealing Club",
    "mcd_05_04": "The Wheelchair's Future of the Universe",
    "mcd_scoow06_02": "DesireDrive",
    "mcd_01_13": "The Curious Everyday Life of the Flying Shrine Maiden",
    "th075_20": "Eastern Forgathering Dream",
    "th01_08": "Small Evil-Crushing Blade",
    "th02_18": "Demon-Sealing Finale"
}