{
    "reimu-1": "Spirit Sign \"Fantasy Seal\"",
    "reimu-2": "Divine Arts \"Omnidirectional Dragon-Slaying Circle\"",
    "reimu-3": "Treasure \"Ying-Yang Asuka'i\"",
    "marisa-story-1": "Star Love Sign \"Sprinkle Star & Heart\"",
    "marisa-1": "Love Sign \"Master Spark\"",
    "marisa-2": "Comet \"Blazing Star\"",
    "marisa-3": "Star Sign \"Satellite Illusion\"",
    "kasen-1": "Wrap Sign \"Prosthetic Arm Proteus\"",
    "kasen-2": "Dragon Sign \"Dragon's Growl\"",
    "kasen-3": "Hawk Sign \"Hawk Beacon\"",
    "ichirin-1": "Storm Sign \"Autumn Storm Clouds of Buddhist Retribution\"",
    "ichirin-2": "Cumulonimbus \"Foreseeing Nyuudou Cloud\"",
    "ichirin-3": "Clenched Fist \"Deadly Wind of Penitence\"",
    "ichirin-story-1": "Fist Wind Sign \"Nyuudou Murakumo Feng Shui Fist\"",
    "hijiri-1": "Heaven Sign \"Master of the Great Trichiliocosm\"",
    "hijiri-2": "Heaven Sign \"Brilliance of Mahavairocana\"",
    "hijiri-3": "Heaven Sign \"Five-Element Mountain of Shakyamuni\"",
    "futo-1": "Wind Sign \"Miwa Plate Storm\"",
    "futo-2": "Blaze Sign \"Taiyi True Fire\"",
    "futo-3": "Fate \"Gate Opening for Catastrophe\"",
    "miko-1": "Hermit Sign \"Taoist of the Land of the Rising Sun\"",
    "miko-2": "Tao Sign \"Heavenly Way Atop One's Palm\"",
    "miko-3": "Human Sign \"Tradition of Just Rewards\"",
    "miko-story-1": "Light Strike Sign \"Vajra Shoot of the Royal Road that Guides You\"",
    "mamizou-1": "Transformation \"Bunbuku Hot Soup Bathtub\"",
    "mamizou-2": "Transformation \"Youkai World Gate of One Hundred Demons\"",
    "mamizou-3": "Transformation \"Futatsuiwa Clan's Curse\"",
    "mamizou-story-1": "Transform Fire Sign \"Youkai Danmaku Transformation: Dry Leaf Detonation\"",
    "mokou-1": "Blaze Sign \"Self-Destruction Giant Flame Whirlwind\"",
    "mokou-2": "Undying \"'South Wind, Clear Sky' Soaring Kick\"",
    "mokou-3": "Cursed Talisman \"Indiscriminate Ignition Cards\"",
    "sinmyoumaru-1": "Mallet \"Lavish Banquet of Legend\"",
    "sinmyoumaru-2": "Inchling \"One-Inch Samurai with a Half-Inch Soul\"",
    "sinmyoumaru-3": "Fishing Sign \"Adorable Tai Gong Wang\"",
    "nitori-1": "Heavy Rain \"Great War Beneath the River\"",
    "nitori-2": "Bubble Sign \"Fire! Bubble Dragon\"",
    "nitori-3": "Battle Machine \"Fly! Sanpei Fight\"",
    "nitori-story-1": "Water Mask Sign \"Water Balloon Masquerade\"",
    "koishi-1": "Suppression \"Superego\"",
    "koishi-2": "Instinct \"Release of the Id\"",
    "koishi-3": "Dream Sign \"Ancestors are Watching You\"",
    "kokoro-1": "Angry Mask \"Mask of an Angry Hated Wolf\"",
    "kokoro-2": "Possession \"Four Humors Possession\"",
    "kokoro-3": "Melancholy Mask \"The Man of Qi Worries about the Earth\"",
    "usami-1": "Gun Sign \"3D Printer Gun\"",
    "usami-2": "Psychokinesis \"Psychokinesis App\"",
    "usami-3": "Psychokinesis \"Telekinesis: Radio Tower\"",
    "sumireko-story-1": "Double ESP \"Psychokinesis Teleportation\"",
    "sumireko-story-2": "Double ESP \"Desperate Danger Metropolitan\"",
    "udonge-1": "\"Lunar Surface Ricochet (Lunatic Double)\"",
    "udonge-2": "\"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)\"",
    "udonge-3": "\"Earth's Surface Ricochet (Lunatic Echo)\"",
    "doremy-1": "Dream Sign \"Deep Navy Runaway Dream\"",
    "doremy-2": "Dream Sign \"Pitch-Black Cosmic Dream\"",
    "doremy-3": "Sheep Sign \"Nightmare of Chimera\"",
    "yukari-1": "\"Unmanned Abandoned Railroad Car Bomb\"",
    "yukari-2": "Shikigami \"Ran Yakumo & Chen\"",
    "yukari-3": "Boundary \"Overflowing Flotsam\"",
    "yukari-story-1": "\"Spirit {{ruby|Master's|Medium's}} Melancholy\"",
    "yukari-story-2": "\"Perfect Possession and Fantasy Seal\"",
    "yukari-story-3": "\"Boundary of {{ruby|Spirit Medium|Master}} and {{ruby|Divine Spirit|Slave}}\"",
    "tenshi-1": "Keystone \"Kaname Funnel\"",
    "tenshi-story-3": "\"Rebuild the Whole Land Into a World of Dreams!\"",
    "tenshi-story-1": "Rise Sign \"Soar to Distant Skies, Carrying Our Dreams!\"",
    "tenshi-3": "Peach Sign \"Hermit's Peach of Steadfast Durability\"",
    "tenshi-2": "Earth Sign \"Qian & Kun Earthquake Strike\"",
    "tenshi-story-2": "Plummet Sign \"Falling Through the Atmosphere, Dreams Rain Down Upon the Ground\"",
    "jyoon-2": "Poor Sign \"Super Poverty Bomb\"",
    "jyoon-1": "Possession Stripping \"Slave Robber\"",
    "joon-story-3": "Possession Exchange \"Absolute Loser\"",
    "joon-story-1": "Bad Luck \"Welcome to the World of Destitution\"",
    "jyoon-3": "\"Queen of Bubble\"",
    "shion-story-2": "\"The Most Despicable and Disastrous God of Destitution and Misery\"",
    "shion-story-1": "Poor Sign \"Mischance Scatter\"",
    "joon-story-2": "Financial Ruin \"Pluck Pigeon\"",
    "reimu-story-1": "Spirit Hawk Sign \"Fantasy Seal Hunting Done by a Hawk\"",
    "marisa-story-2": "Star Spirit Sign \"Sprinkle Star Seal\"",
    "hijiri-story-1": "Strike Fist Sign \"Skanda's Strange Cloud Fist\"",
    "koishi-story-1": "Love Fist Sign \"Rose Capriccio's Strange Cloud Fist\"",
    "kokoro-story-1": "Mask Wind Sign \"Four Humors' Feng Shui Art\"",
    "reisen-story-1": "Mad Mallet Sign \"Disorder Eyes (Lunatic Stare Illusions) Grow Bigger, Too!\"",
    "tenshi-story-4": "Rising Mallet Sign \"Carry Our Dreams and Grow Bigger!\"",
    "tenshi-story-5": "Plummeting Mallet Sign \"Dreams Fall Through the Atmosphere and Grow Bigger!\"",
    "reimu-lw": "*To Think There'd be a Shrine Maiden in That Gap!*",
    "kasen-lw": "*Monkey's Paw! Crush My Enemies!*",
    "marisa-lw": "*Lovely! Miss Hanako of the Toilet!*",
    "jyoon-lw": "\"Extortioner of the 80's\"",
    "tenshi-lw": "*All of the Atmosphere is Within My Reach!*",
    "yukari-lw": "*Lend Me Those Beautiful Legs!*",
    "doremy-lw": "*There's No Need to Wake Up Anymore*",
    "udonge-lw": "*You've Already Gone Mad!*",
    "usami-lw": "*See Visions of the Other World's Lunacy!*",
    "kokoro-lw": "*I'm Still Pretty Like This, Right?*",
    "koishi-lw": "*I'm Going to Call You Now, So Answer the Phone!*",
    "nitori-lw": "*Loch Ness is Here Now!*",
    "mokou-lw": "*Let the Whole World Burn Away to Nothing!*",
    "ichirin-lw": "*The 265-Centimeter Fiend Appears!*",
    "futo-lw": "*Even in Death, One Plate is Missing!*",
    "hijiri-lw": "*Race Through the Sky at 100 km/h!*",
    "miko-lw": "*As a Special Service, I'll Let You Choose Both!*",
    "mamizou-lw": "*Space Security Leak! Deal With the Situation Promptly!*",
    "sinmyoumaru-lw": "*Grow Bigger, Oh Green Giant!*",
    "reimu-story-against-shion": "\"The Most Powerful and Fortuitous Shrine Maiden of Incident Resolution\"",
    "reimu-story-2": "Spirit Sign \"Fantasy Seal -Dreamfinite-\"",
    "marisa-story-4": "Needle Star Sign \"Needle Spark to Seal the Lunar Nobles\"",
    "marisa-story-3": "Star Sign \"Asteroid Belt Nightmare\"",
    "kasen-story-2": "Dragon Kick Sign \"Dragon's Asuka'i Kick\"",
    "kasen-story-1": "Thunder Spirit Sign \"Mukou's Thunder Shot Fantasy Seal\"",
    "kasen-story-3": "Thunder Sign \"Mukou's Thunderbolt Flash Fantasy Bullet\"",
    "kasen-story-4": "Dragon Sign \"Dragon's Optical Dream\"",
    "kasen-story-6": "Dragoning Sign \"Dragon's Alien Capsule\"",
    "ichirin-story-3": "Fist Water Sign \"Nyuudou Murakumo Water Bomb Fist\"",
    "ichirin-story-2": "Fist Star Sign \"Nyuudou Murakumo Slave Spark\"",
    "hijiri-story-od": "Light Hermit Sign \"Monk & Taoist of the Land of the Rising Sun\"",
    "hijiri-story-5": "Light Fist Sign \"Indra Varja Strange Cloud Fist\"",
    "hijiri-story-3": "Kick Slash Sign \"Garuda's Shoutoku Slash\"",
    "hijiri-story-4": "Strike Sign \"Prophetic Dream of Pursuit by Skanda\"",
    "hijiri-story-2": "Strike Light Sign \"Glory of Skanda's Noble Path\"",
    "futo-story-1": "Wind Spirit Sign \"Iwafune Kawarake Seal\"",
    "miko-story-3": "Light Wind Sign \"Radiant Feng Shui Cape\"",
    "miko-story-2": "Light Sign \"Glory of the Noble Dream Path that Guides You\"",
    "mamizou-story-2": "Transform Sign \"Youkai Danmaku Transformation: Dreamy State of Mind\"",
    "kasen-story-5": "Thundering Sign \"Mukou to Dry Leaf Danmaku Transformation\"",
    "mokou-story-1": "Fire Madness Sign \"{{ruby|Human Combustion Concealment Danmaku|Burning Hidden Bullet}}\"",
    "mokou-story-2": "\"Until This Life, Repeated Countless Times, Gets Fantasy-Sealed Away\"",
    "shinmyoumaru-story-3": "Mallet Pebble Sign \"Jingling Gold Pile Psychokinesis\"",
    "shinmyoumaru-story-2": "Mallet Transform Sign \"Wild Riches Danmaku Transformation\"",
    "shinmyoumaru-story-1": "Mallet Love Sign \"Rolling-in-Riches Heart\"",
    "kokoro-story-2": "Mask Sign \"Four Humours' Maddening Masquerade\"",
    "sumireko-story-od": "\"Double ESPer of the Century, Sumireko Usami\"",
    "sumireko-story-3": "ESP \"Psychokinesis Endless\"",
    "doremy-story-2": "Dream Keystone Sign \"Wool-Colored Toss Staking Heaven & Earth\"",
    "doremy-story-1": "Dream Rubble Sign \"Wool-Colored Psychokinesis\"",
    "tenshi-story-od-3": "\"Sky of Scarlet Perception of Space People\"",
    "tenshi-story-od-2": "\"A Huge Battleship: 'Invincible Catfish' Is Approaching Fast!\"",
    "tenshi-story-od-1": "\"Sky of Scarlet Perception of All Inchlings\""
}