{
    "id": "thpatch",
    "title": "Touhou Patch Center",
    "contact": "network@thpatch.net",
    "neighbors": [
        "https://mirrors.thpatch.net/nmlgc/",
        "https://raw.githubusercontent.com/Ghildrean/touhou-es-es/master/",
        "https://raw.githubusercontent.com/Gamer251/thcrap-gamer251/master/",
        "https://raw.githubusercontent.com/soap925/BurntToast-Mod-Stockhouse/master/",
        "https://raw.githubusercontent.com/Nutzer/Touhou-8.3/master/",
        "https://raw.githubusercontent.com/Zrrg/UnKnwn/master/",
        "https://raw.githubusercontent.com/DTM9025/DTM/master/",
        "https://mirrors.thpatch.net/wobuffet3/",
        "https://mirrors.thpatch.net/PookChang'e/",
        "https://mirrors.thpatch.net/MasterGameFTW3561/",
        "https://raw.githubusercontent.com/Tearff/Tear/master/",
        "https://raw.githubusercontent.com/GhostPhanom/GhostPhanom-Thcrap/master/",
        "https://mirrors.thpatch.net/Bravi/",
        "https://raw.githubusercontent.com/Priw8/thmod/master/",
        "https://mirrors.thpatch.net/Splashman/",
        "https://mirrors.thpatch.net/MoriyaFaith/",
        "https://mirrors.thpatch.net/PKWeegee/",
        "https://mirrors.thpatch.net/dass7/",
        "https://raw.githubusercontent.com/SMB7/SMB3Memes/master/",
        "https://raw.githubusercontent.com/WindowDump/thcrap_mods/master/",
        "https://mirrors.thpatch.net/Vasteel/",
        "https://raw.githubusercontent.com/Daikarasu/DaiMod/master/",
        "https://mirrors.thpatch.net/Clover/",
        "https://raw.githubusercontent.com/32th-System/crap/master/",
        "https://mirrors.thpatch.net/Gensokyo.EXE/",
        "https://mirrors.thpatch.net/pgj1997/",
        "https://raw.githubusercontent.com/rosenrose/thmod/master/",
        "https://mirrors.thpatch.net/AsyrafFile/",
        "https://raw.githubusercontent.com/ExpHP/thcrap-patches/master/patches/",
        "https://raw.githubusercontent.com/Arandui/trash_patch/master/",
        "https://mirrors.thpatch.net/tpZHCNex/",
        "https://raw.githubusercontent.com/bttf0504/thmod/master/",
        "https://raw.githubusercontent.com/chrisGrando/thcrap-patches/master/",
        "https://mirrors.thpatch.net/sqrt/",
        "https://mirrors.thpatch.net/someguy/",
        "https://mirrors.thpatch.net/LmocinemodPatchRepo/",
        "https://raw.githubusercontent.com/zero318/thcrap_patches/master/patches/",
        "https://raw.githubusercontent.com/PartyParrotTH/PartyParrot-s-Patches-Repository/master/",
        "https://mirrors.thpatch.net/WilliamDavi/",
        "https://mirrors.thpatch.net/shirokura/",
        "https://raw.githubusercontent.com/yeashie/yeashiePatches/master/",
        "https://mirrors.thpatch.net/redirectto/",
        "https://mirrors.thpatch.net/Revenant/",
        "https://raw.githubusercontent.com/WishMakers0/th_crap/master/",
        "https://mirrors.thpatch.net/Guy/",
        "https://raw.githubusercontent.com/KabanFriends/THGTE/master/",
        "https://mirrors.thpatch.net/Shoxlu/",
        "https://mirrors.thpatch.net/Kogasas_Mods/",
        "https://mirrors.thpatch.net/TESM/",
        "https://mirrors.thpatch.net/Clb184/",
        "https://mirrors.thpatch.net/Wasted/",
        "https://raw.githubusercontent.com/BrosterMedia/touhoupatches/main/",
        "https://mirrors.thpatch.net/egor/",
        "https://mirrors.thpatch.net/mintymods/",
        "https://mirrors.thpatch.net/yova/",
        "https://mirrors.thpatch.net/SuperChrim/",
        "https://mirrors.thpatch.net/TRDario/",
        "https://mirrors.thpatch.net/yuureiki/",
        "https://mirrors.thpatch.net/tpZHCHTex/",
        "https://mirrors.thpatch.net/farawayvision/",
        "https://raw.githubusercontent.com/megapig9001/megapig9001-mods/main/",
        "https://mirrors.thpatch.net/SSM/",
        "https://mirrors.thpatch.net/catysumi/catysumi/",
        "https://mirrors.thpatch.net/DedeHead/",
        "https://mirrors.thpatch.net/neonickz/",
        "https://mirrors.thpatch.net/Wast/",
        "https://mirrors.thpatch.net/Daichungus/",
        "https://mirrors.thpatch.net/RogyWantsCoffee/"
    ],
    "url_desc": "http://thpatch.net/wiki/Category:Patches",
    "servers": [
        "https://srv.thpatch.net/"
    ],
    "patches": {
        "lang_mk": "Macedonian language pack",
        "lang_mn": "Mongolian language pack",
        "lang_ms": "Malay language pack",
        "lang_ms-jawi": "Malay (Jawi script)",
        "lang_ms-kel": "Kelantanese Malay language pack",
        "lang_ms-simple": "Simplified Malay language pack",
        "lang_nb": "Norwegian (Bokmål) language pack",
        "lang_ncs": "Necarasso Cryssesa language pack",
        "lang_nl": "Dutch language pack",
        "lang_nl-informal": "Dutch (informal) language pack",
        "lang_pig": "Pig Latin language pack",
        "lang_pl": "Polish language pack",
        "lang_pl-tvp": "Polish Wieczorynka language pack",
        "lang_pt": "Portuguese language pack",
        "lang_pt-br": "Brazilian Portuguese language pack",
        "lang_pt-br-lol": "Brazilian Portuguese troll translations",
        "lang_pt-br-weeb": "Brazilian Portuguese Weeaboo translations",
        "lang_qu": "Quechua language pack",
        "lang_ro": "Romanian language pack",
        "lang_ru": "Russian language pack",
        "lang_ru-hepburn": "Russian alternative (Hepburn)",
        "lang_ru-latin": "Russki (Latinica)",
        "lang_ru-prereform": "Pre-reform Russian language pack",
        "lang_sah": "Сахалыы тылбаас",
        "lang_sco": "Scots language pack",
        "lang_sk": "Slovak language pack",
        "lang_sr": "Serbian language pack",
        "lang_sr-lol": "Serbian troll translations",
        "lang_sv": "Swedish language pack",
        "lang_th": "Thai language pack",
        "lang_th-lol": "Thai troll translations",
        "lang_tl": "Tagalog language pack",
        "lang_tlh": "Klingon language pack",
        "lang_tokipona": "Toki Pona language pack",
        "lang_tokipona-sp": "Toki Pona language pack - sitelen pona script",
        "lang_tr": "Turkish language pack",
        "lang_uk": "Ukrainian language pack",
        "lang_vec": "Venetian language pack",
        "lang_vi": "Vietnamese community translations",
        "lang_vi-lol": "Vietnamese troll translations",
        "lang_vi-thvnfb": "Vietnamese translations by THVNFB",
        "lang_zh-hans": "Simplified Chinese language pack",
        "lang_zh-hant": "Traditional Chinese language pack",
        "lang_zh-hant-hk": "Traditional HK Chinese language pack",
        "lang_zh-hant-tw": "Traditional Taiwan Chinese language pack",
        "nojoy": "Disable joystick support",
        "sandbox": "Patch development sandbox (unstable)",
        "skipgame": "Skip gameplay sections",
        "cue": "Scoring cues",
        "lang_ar": "Arabic language pack",
        "lang_ar-lb": "Lebanese Arabic language pack",
        "lang_ar-lol": "Arabic troll translations",
        "lang_arz": "Egyptian Arabic language pack",
        "lang_az": "Azərbaycanca language pack",
        "lang_be": "Belarusian language pack",
        "lang_bg": "Bulgarian language pack",
        "lang_bn": "Bengali language pack",
        "lang_ce": "Chechen language pack",
        "lang_cs": "Czech language pack",
        "lang_de": "German language pack",
        "lang_de-bing": "Bing Translate, Japanese -> German",
        "lang_de-ch": "Swiss High German differences",
        "lang_de-lol": "Deutsch (meta)",
        "lang_el": "Greek language pack",
        "lang_en": "English language pack",
        "lang_en-4kids": "Mysteryland Project",
        "lang_en-alt": "Alternate English language pack",
        "lang_en-arr": "Pirate English language pack",
        "lang_en-ca": "Canadian English differences",
        "lang_en-deepl": "English translated by DeepL language pack",
        "lang_en-gb": "British English differences",
        "lang_en-google": "Google Translate, Japanese -> English",
        "lang_en-literal": "Literal English language pack",
        "lang_en-lol": "English troll translations",
        "lang_en-preta": "Preta's English language pack",
        "lang_en-tyke": "Yorkshire English language pack",
        "lang_en-yoda": "English as spoken by Yoda from Star Wars",
        "lang_eo": "Esperanto language pack",
        "lang_es": "Spanish community translations",
        "lang_es-419": "Latin American Spanish language pack",
        "lang_es-ar": "Argentine Spanish language pack",
        "lang_es-cl": "Chilean Spanish language pack",
        "lang_es-hourai": "Spanish translations by the Hourai Doll team",
        "lang_es-ht": "Latin American Spanish (History Translator translation)",
        "lang_es-mx": "Mexican Spanish language pack",
        "lang_es-pob": "Latin American Spanish (Paradise of Boundaries translation)",
        "lang_es-suzunaan": "Suzunaan's European Spanish language pack",
        "lang_es-ve": "Venezuelan Spanish language pack",
        "lang_es-ve-lol": "Venezuelan Spanish troll translations",
        "lang_fa": "Persian language pack",
        "lang_fi": "Finnish language pack",
        "lang_fr": "French language pack",
        "lang_fr-lol": "French troll translations",
        "lang_fr-qc-fo": "Quebec French language pack",
        "lang_gsw": "Swiss German language pack",
        "lang_he": "Hebrew language pack",
        "lang_hi": "Hindi language pack",
        "lang_hr": "Croatian language pack",
        "lang_hu": "Hungarian language pack",
        "lang_id": "Indonesian language pack",
        "lang_it": "Italian language pack",
        "lang_ithkuil": "Ithkuil language pack",
        "lang_it-lol": "Italian troll translations",
        "lang_ja": "Japanese language pack",
        "lang_jbo": "Lojban language pack",
        "lang_jv": "Javanese language pack (Latin script)",
        "lang_ko": "Korean language pack",
        "lang_ku": "Kurdish language pack",
        "lang_la": "Latin language pack",
        "lang_lb": "Luxembourgish language pack",
        "lang_sr-literal": "Literal Serbian language pack",
        "lang_la-machine": "Latin translation with the help of machine translation",
        "lang_ga": "Gaelic language pack",
        "lang_ja-furigana": "Japanese with Furigana",
        "lang_ru-goblin": "Goblin Russian language pack",
        "lang_ar-gulf": "Gulf Arabic language pack",
        "lang_tr-lol": "Turkish troll translations",
        "noprank": "Removes any pranks we might pull on you (pick last)",
        "lang_nn": "Norwegian Nynorsk language pack",
        "lang_pnb": "Punjabi translation (Shahmukhi Abjad)",
        "lang_aeb": "Tunisian Arabic language pack",
        "lang_gn-jopara": "Jopara language pack",
        "lang_es-peru": "Peruvian Spanish language pack"
    }
}